---
title: "osplot"
author: "郑元瑞"
date: "2022/4/5"
output: html_document
---
# 加载包
```{r}
library(tidyverse)
library(readxl)
library(treemapify)
library(ggthemes)
library(here)
```

# 读取数据

## Open Scholarship Grassroots Community Networks
```{r}
df.OSGCN <- read_excel(here("data", "Open Scholarship Grassroots Community Networks.xlsx")) %>% dplyr::select(...1, developed, country) %>% rename("organization" = ...1)
df.OSGCN$country <- str_squish(df.OSGCN$country)
```
```{r}

df.OSGCN <- df.OSGCN %>% filter(
organization != "Helmholtz Open Science Coordination Office")
df.OSGCN <- df.OSGCN %>% filter(
organization != "Netzwerk der Open Science Initiativen (NOSI)")
df.OSGCN <- df.OSGCN %>% filter(
organization != "Netzwerk der Open Science Initiativen (NOSI), Germany")
df.OSGCN <- df.OSGCN %>% filter(
organization != "Leibniz Research Alliance Open Science")


df.OSGCN <- df.OSGCN %>% 
  mutate(rep_code = case_when(
  country == "Egypt" ~ "EGY", 
  country == "Hungary" ~ "HUN", 
  country == "USA" ~ "USA", 
  country == "United Kingdom"~ "GBR", 
  country == "Nigeria" ~ "NIG", 
  country =="France"~ "FRA", 
    country =="Canada" ~ "CAN", 
    country == "Germany" ~ "DEU", 
    country =="Australia"  ~ "AUS", 
    country =="Kenya" ~ "KEN", 
    country =="Netherlands" ~ "NLD", 
    country =="Brazil" ~ "BRA", 
    country =="China" ~ "CHN", 
    country =="Mozambique" ~ "MOZ", 
    country =="Tunisia" ~ "TUN", 
    country =="Bangladesh" ~ "BGD",
    country =="Romania" ~ "ROU",
    country =="Denmark" ~ "DNK",
    country =="Scotland" ~ "GBR",
    country =="Sweden" ~ "SWE",
    country =="Ghana" ~ "GHA",
    country =="Iceland" ~ "ISL",
    country =="Chile" ~ "CHL",
    country =="Austria" ~ "AUT",
    country =="Indonesia" ~ "IDN",
    country =="Colombia" ~ "COL",
    country =="Pakistan" ~ "PAK",
    country =="New Zealand" ~ "NZL",
    country =="Turkey" ~ "TUR",
    country =="Ukraine" ~ "UKL",
    country =="Mexico" ~ "MEX",
    country =="India" ~ "IND",
    country =="Ethiopia"~ "ETH",
    country =="Philippines"~ "PHL",
    country =="Uganda" ~  "UGA",
    country =="Wales" ~ "GBR",
    country =="South Africa" ~ "ZAF",
    country =="Italy" ~ "ITA",
    country =="Switzerland" ~ "CHE",
    country =="Iran" ~ "IRN",
    country =="spain" ~ "ESP",
    country =="Sudan" ~ "SDN",
    country =="Czech Republic" ~ "CZE",
    country =="Belgium" ~ "BEL",
    country =="Cyprus" ~ "CY",
   country == "UK" ~ "GBR", 
  country == "swiss" ~ "CHE",
    country == "Sweden" ~ "SWE",
    country =="German" ~ "DEU",
    country =="Australia" ~ "AUS",
    country == "Portugal" ~ "PRT",
    country == "Norway" ~ "NOR",
    country == "Italy" ~ "ITA",
    country == "Finland"  ~ "FIN",
    country == "Brazil" ~ "BRA", 
  country == "Poland" ~ "POL", 
  country == "United States"~ "USA", 
  country =="Japan" ~ "JPN", 
  country =="Iran, Islamic Republic of" ~ "IRN", 
  country =="Russian Federation" ~ "RUS", 
  country == "Ireland" ~ "IRL",
  country == "Nepal" ~ "NP", 
  country == "The Republic of Senegal" ~ "SEN",
  country == "AU and NZ" ~ "AU and NZ"
))


df.OSGCN[is.na(df.OSGCN) == TRUE] <- "NA"
df.OSGCN <- df.OSGCN %>% mutate(platform = "OSGCN")
```




## osambassador
```{r}
df.osam <- read_excel(here("data", "osambassador.xlsx")) %>% 
  select(name, country, deveploed) %>% rename(developed = deveploed)
df.osam$country <- str_squish(df.osam$country)

df.osam <- df.osam %>% mutate(rep_code = case_when(
  country == "Egypt" ~ "EGY", 
  country == "Hungary" ~ "HUN", 
  country == "USA" ~ "USA", 
  country == "United Kingdom"~ "GBR", 
  country == "Nigeria" ~ "NIG", 
  country =="France"~ "FRA", 
    country =="Canada" ~ "CAN", 
    country == "Germany" ~ "DEU", 
    country =="Australia"  ~ "AUS", 
    country =="Kenya" ~ "KEN", 
    country =="Netherlands" ~ "NLD", 
    country =="Brazil" ~ "BRA", 
    country =="China" ~ "CHN", 
    country =="Mozambique" ~ "MOZ", 
    country =="Tunisia" ~ "TUN", 
    country =="Bangladesh" ~ "BGD",
    country =="Romania" ~ "ROU",
    country =="Denmark" ~ "DNK",
    country =="Scotland" ~ "GBR",
    country =="Sweden" ~ "SWE",
    country =="Ghana" ~ "GHA",
    country =="Iceland" ~ "ISL",
    country =="Chile" ~ "CHL",
    country =="Austria" ~ "AUT",
    country =="Indonesia" ~ "IDN",
    country =="Colombia" ~ "COL",
    country =="Pakistan" ~ "PAK",
    country =="New Zealand" ~ "NZL",
    country =="Turkey" ~ "TUR",
    country =="Ukraine" ~ "UKL",
    country =="Mexico" ~ "MEX",
    country =="India" ~ "IND",
    country =="Ethiopia"~ "ETH",
    country =="Philippines"~ "PHL",
    country =="Uganda" ~  "UGA",
    country =="Wales" ~ "GBR",
    country =="South Africa" ~ "ZAF",
    country =="Italy" ~ "ITA",
    country =="Switzerland" ~ "CHE",
    country =="Iran" ~ "IRN",
    country =="spain" ~ "ESP",
    country =="Sudan" ~ "SDN",
    country =="Czech Republic" ~ "CZE",
    country =="Belgium" ~ "BEL",
    country =="Cyprus" ~ "CY",
)) %>% mutate(platform = "COS ambassador")
```








## UK
```{r}
df.UK <- read_excel(here("data", "uk.xlsx")) %>% mutate(rep_code = case_when(
  country == "UK" ~ "GBR", 
  country == "swiss" ~ "CHE",
    country == "Sweden" ~ "SWE",
    country =="German" ~ "DEU",
    country =="Australia" ~ "AUS",
    country == "Portugal" ~ "PRT",
    country == "Norway" ~ "NOR",
    country == "Italy" ~ "ITA",
    country == "Finland"  ~ "FIN",
    country == "Brazil" ~ "BRA",
)) %>% mutate(platform = "Reproducibility Network")

```
## Tea

```{r}
df.tea <- read_excel(here("data", "ReproducibiliTea.xlsx")) %>% 
  mutate(rep_code = case_when(
  country == "Egypt" ~ "EGY", 
  country == "Hungary" ~ "HUN", 
  country == "USA" ~ "USA", 
  country == "United Kingdom"~ "GBR", 
  country == "Nigeria" ~ "NIG", 
  country =="France"~ "FRA", 
    country =="Canada" ~ "CAN", 
    country == "Germany" ~ "DEU", 
    country =="Australia"  ~ "AUS", 
    country =="Kenya" ~ "KEN", 
    country =="Netherlands" ~ "NLD", 
    country =="Brazil" ~ "BRA", 
    country =="China" ~ "CHN", 
    country =="Mozambique" ~ "MOZ", 
    country =="Tunisia" ~ "TUN", 
    country =="Bangladesh" ~ "BGD",
    country =="Romania" ~ "ROU",
    country =="Denmark" ~ "DNK",
    country =="Scotland" ~ "GBR",
    country =="Sweden" ~ "SWE",
    country =="Ghana" ~ "GHA",
    country =="Iceland" ~ "ISL",
    country =="Chile" ~ "CHL",
    country =="Austria" ~ "AUT",
    country =="Indonesia" ~ "IDN",
    country =="Colombia" ~ "COL",
    country =="Pakistan" ~ "PAK",
    country =="New Zealand" ~ "NZL",
    country =="Turkey" ~ "TUR",
    country =="Ukraine" ~ "UKL",
    country =="Mexico" ~ "MEX",
    country =="India" ~ "IND",
    country =="Ethiopia"~ "ETH",
    country =="Philippines"~ "PHL",
    country =="Uganda" ~  "UGA",
    country =="Wales" ~ "GBR",
    country =="South Africa" ~ "ZAF",
    country =="Italy" ~ "ITA",
    country =="Switzerland" ~ "CHE",
    country =="Iran" ~ "IRN",
    country =="spain" ~ "ESP",
    country =="Sudan" ~ "SDN",
    country =="Czech Republic" ~ "CZE",
    country =="Belgium" ~ "BEL",
    country =="Cyprus" ~ "CY",
   country == "UK" ~ "GBR", 
  country == "swiss" ~ "CHE",
    country == "Sweden" ~ "SWE",
    country =="German" ~ "DEU",
    country =="Australia" ~ "AUS",
    country == "Portugal" ~ "PRT",
    country == "Norway" ~ "NOR",
    country == "Italy" ~ "ITA",
    country == "Finland"  ~ "FIN",
    country == "Brazil" ~ "BRA", 
  country == "Poland" ~ "POL", 
  country == "United States"~ "USA", 
  country =="Japan" ~ "JPN", 
  country =="Iran, Islamic Republic of" ~ "IRN", 
  country =="Russian Federation" ~ "RUS", 
  country == "Ireland" ~ "IRL"
)) %>% mutate(platform = "ReproducibiliTea")
```

## SIPS
```{r}
df.SIPS <- read_xlsx(here("data", "SIPS.xlsx")) %>% 
  mutate(rep_code = case_when(
  country == "Egypt" ~ "EGY", 
  country == "Hungary" ~ "HUN", 
  country == "USA" ~ "USA", 
  country == "United Kingdom"~ "GBR", 
  country == "Nigeria" ~ "NIG", 
  country =="France"~ "FRA", 
    country =="Canada" ~ "CAN", 
    country == "Germany" ~ "DEU", 
    country =="Australia"  ~ "AUS", 
    country =="Kenya" ~ "KEN", 
    country =="Netherlands" ~ "NLD", 
    country =="Brazil" ~ "BRA", 
    country =="China" ~ "CHN", 
    country =="Mozambique" ~ "MOZ", 
    country =="Tunisia" ~ "TUN", 
    country =="Bangladesh" ~ "BGD",
    country =="Romania" ~ "ROU",
    country =="Denmark" ~ "DNK",
    country =="Scotland" ~ "GBR",
    country =="Sweden" ~ "SWE",
    country =="Ghana" ~ "GHA",
    country =="Iceland" ~ "ISL",
    country =="Chile" ~ "CHL",
    country =="Austria" ~ "AUT",
    country =="Indonesia" ~ "IDN",
    country =="Colombia" ~ "COL",
    country =="Pakistan" ~ "PAK",
    country =="New Zealand" ~ "NZL",
    country =="Turkey" ~ "TUR",
    country =="Ukraine" ~ "UKL",
    country =="Mexico" ~ "MEX",
    country =="India" ~ "IND",
    country =="Ethiopia"~ "ETH",
    country =="Philippines"~ "PHL",
    country =="Uganda" ~  "UGA",
    country =="Wales" ~ "GBR",
    country =="South Africa" ~ "ZAF",
    country =="Italy" ~ "ITA",
    country =="Switzerland" ~ "CHE",
    country =="Iran" ~ "IRN",
    country =="spain" ~ "ESP",
    country =="Sudan" ~ "SDN",
    country =="Czech Republic" ~ "CZE",
    country =="Belgium" ~ "BEL",
    country =="Cyprus" ~ "CY",
   country == "UK" ~ "GBR", 
  country == "swiss" ~ "CHE",
    country == "Sweden" ~ "SWE",
    country =="German" ~ "DEU",
    country =="Australia" ~ "AUS",
    country == "Portugal" ~ "PRT",
    country == "Norway" ~ "NOR",
    country == "Italy" ~ "ITA",
    country == "Finland"  ~ "FIN",
    country == "Brazil" ~ "BRA", 
  country == "Poland" ~ "POL", 
  country == "United States"~ "USA", 
  country =="Japan" ~ "JPN", 
  country =="Iran, Islamic Republic of" ~ "IRN", 
  country =="Russian Federation" ~ "RUS", 
  country == "Ireland" ~ "IRL"
)) %>% 
  mutate(platform = "SIPS")

```



```{r}
df_all <- rbind(df.UK[c("country", "rep_code", "developed", "platform")], df.osam[c("country", "rep_code", "developed", "platform")], df.tea[c("country", "rep_code", "developed", "platform")], df.OSGCN[c("country", "rep_code", "developed", "platform")], df.SIPS[c("country", "rep_code", "developed", "platform")])
```


```{r}
df_all

unique(df_all$country)
```
```{r}
df.fullname <- df_all %>% 
  mutate(full_name = case_when(
    country == "Iran, Islamic Republic of" ~ "Iran", 
    country == "UK" ~ "United Kingdom",
    country == "swiss" ~ "Switzerland", 
    country == "spain" ~ "Spain",
    country == "Scotland" ~ "UK",
    country == "Wales" ~ "UK",
    country == "The Republic of Senegal" ~ "Senegal",
    country == "Russian Federation" ~ "Russia",
    TRUE ~ as.character(country)
  )) 
# write_csv(df.fullname, "figure1.csv")
```



```{r fig.height=10, fig.width=10}
df_final <- df.fullname %>% group_by(full_name, developed, platform) %>% 
  summarise(n = n()) %>% 
  mutate(developed = case_when(developed == 1 ~ "Developed",
                               developed == 0 ~"Developing",
                               developed == "NA"~ "Not Available")) 
df_final$developed <- factor(df_final$developed, levels = c("Developed", "Developing", "Not Available"))
id <- unique(df_final$platform)
df_na <- df_final %>% 
  filter(developed == "Not Available") %>%
mutate(full_name = case_when(
  full_name == "NA" ~ " "
)) 
df_final.f <- df_final %>% filter(full_name != "NA")
df_final <- rbind(df_final.f, df_na)
df_final <- df_final %>% ungroup()
```


```{r}
df.cos_plot <- df_final %>% 
  filter(platform == "COS ambassador") %>% 
  ggplot(aes(area = n, fill = developed, label=full_name, 
             subgroup = developed, subgroup2 = full_name)) +
  geom_treemap() +
  geom_treemap_subgroup_border(colour = "grey", size = 10) +
    geom_treemap_subgroup2_border(colour = "grey", size = 5) +
  geom_treemap_text(grow = T, reflow = T, colour = "white", place = "middle") +
  scale_fill_manual(
     values =  c("#99d594", "#fed976", "#D9E2F3")
  ) +
  theme(
       #分面标题字体
      #legend.title=element_text(size =60), #图例标题字体
      #legend.text = element_text(size=60),#图例字体
      legend.box = "bottom") + #水平放
  guides(fill = "none") + ggtitle("Center For Open Science")+ 
  theme(plot.title = element_text(hjust = 0.5, size = 40, face = "bold")) 

# ggsave(filename = "COS.png", plot = df.cos_plot, width = 48, height = 20, dpi = 300)
# df.cos_plot
```

```{r}

df.OSGCN_plot <- df_final %>% 
  filter(platform == "OSGCN") %>% 
  ggplot(aes(area = n, fill = developed, label=full_name, 
             subgroup = developed, subgroup2 = full_name)) +
  geom_treemap() +
  geom_treemap_subgroup_border(colour = "grey", size = 10) +
    geom_treemap_subgroup2_border(colour = "grey", size = 5) +
  geom_treemap_text(grow = T, reflow = T, colour = "white", place = "middle") +
  scale_fill_manual(
     values = c("#3288bd", "#fc9272", "#e0f3f8")
  ) +
   theme(
      legend.title=element_text(size =55), #图例标题字体
      legend.text = element_text(size=55, family="Times New Roman", face = "bold"),#图例字体
      legend.key.size = unit(80, "pt"),
       legend.position = "bottom") + #水平放
  guides(fill = guide_legend("")) + ggtitle("Open Science Grassroots Networks") +
  theme(plot.title = element_text(hjust = 0.5, size = 40, face = "bold")) 

# ggsave(filename = "OSGCN.png", plot = df.OSGCN_plot, width = 48, height = 20, dpi = 300)
# df.OSGCN_plot

```

```{r}
df.ReproducibiliTea_plot <- df_final %>% 
  filter(platform == "ReproducibiliTea") %>% 
  ggplot(aes(area = n, fill = developed, label=full_name, 
             subgroup = developed, subgroup2 = full_name)) +
  geom_treemap() +
  geom_treemap_subgroup_border(colour = "grey", size = 10) +
    geom_treemap_subgroup2_border(colour = "grey", size = 5) +
  geom_treemap_text(grow = T, reflow = T, colour = "white", place = "middle") +
  scale_fill_manual(
     values =  c("#99d594", "#fed976", "#D9E2F3")
  ) +
  theme(
       #分面标题字体
      #legend.title=element_text(size =60), #图例标题字体
     # legend.text = element_text(size=60),#图例字体
      legend.box = "horizontal") + #水平放
  guides(fill = "none") + ggtitle("ReproducibiliTea") + 
  theme(plot.title = element_text(hjust = 0.5, size = 40, face = "bold")) 

# ggsave(filename = "ReproducibiliTea.png", plot = df.ReproducibiliTea_plot, width = 48, height = 20, dpi = 300)
# df.ReproducibiliTea_plot
```

```{r}
df.SIPS_plot <- df_final %>% 
  filter(platform == "SIPS") %>% 
  ggplot(aes(area = n, fill = developed, label=full_name, 
             subgroup = developed, subgroup2 = full_name)) +
  geom_treemap() +
  geom_treemap_subgroup_border(colour = "grey", size = 10) +
    geom_treemap_subgroup2_border(colour = "grey", size = 5) +
  geom_treemap_text(grow = T, reflow = T, colour = "white", place = "middle") +
  scale_fill_manual(
     values =  c("#99d594", "#fed976", "#D9E2F3")
  ) +
  theme(
       #分面标题字体
      #legend.title=element_text(size =60), #图例标题字体
      #legend.text = element_text(size=60),#图例字体
      legend.box = "horizontal") + #水平放
  guides(fill = "none") + ggtitle("SIPS") + 
  theme(plot.title = element_text(hjust = 0.5, size = 40, face = "bold")) 
# ggsave(filename = "SIPS.png", plot = df.SIPS_plot, width = 48, height = 20, dpi = 300)
# df.SIPS_plot
```
```{r}
df.ReproducibilityNetwork_plot <- df_final %>% 
  filter(platform == "Reproducibility Network") %>% 
  ggplot(aes(area = n, fill = developed, label=full_name, 
             subgroup = developed, subgroup2 = full_name)) +
  geom_treemap() +
  geom_treemap_subgroup_border(colour = "grey", size = 10) +
    geom_treemap_subgroup2_border(colour = "grey", size = 5) +
  geom_treemap_text(grow = T, reflow = T, colour = "white", place = "middle") +
  scale_fill_manual(
     values =  c("#99d594", "#fed976", "#D9E2F3")
  ) +
  theme(
       #分面标题字体
      #legend.title=element_text(size =60), #图例标题字体
      #legend.text = element_text(size=60),#图例字体
      legend.box = "horizontal") + #水平放
  guides(fill = "none") + ggtitle("Reproducibility Network") + 
  theme(plot.title = element_text(hjust = 0.5, size = 40, face = "bold")) 
  

# ggsave(filename = "ReproducibilityNetwork.png", plot = df.ReproducibilityNetwork_plot, width = 48, height = 20, dpi = 300)
#df.ReproducibilityNetwork_plot

```

## put plots together
```{r}
library(patchwork)




# osgcn <- df.OSGCN_plot + theme(plot.margin = unit(c(50,100,50,100), "pt"))
# cos <- df.cos_plot+theme(plot.margin = unit(c(0,100,50,0), "pt"))
# tea <- df.ReproducibiliTea_plot+ theme(plot.margin = unit(c(0,100,50,100), "pt"))
# sips <- df.SIPS_plot + theme(plot.margin = unit(c(0,100,50,100), "pt"))

########
osgcn <- df.OSGCN_plot + theme(plot.margin = unit(c(0,100,50,0), "pt"))
cos <- df.cos_plot+theme(plot.margin = unit(c(0,100,50,0), "pt"))
tea <- df.ReproducibiliTea_plot+ theme(plot.margin = unit(c(0,100,50,0), "pt"))
sips <- df.SIPS_plot + theme(plot.margin = unit(c(0,100,50,0), "pt"))
plot_all <-  osgcn/(cos|tea|sips|df.ReproducibilityNetwork_plot) + theme(plot.margin = unit(c(0,0,50,0), "pt"))+
  plot_layout(widths = 1, guides = 'collect')  & 
  theme(legend.position='bottom')

#############

# plot_all <- plot_all + plot_annotation(tag_levels = list(c('a', 'b'), '1')) &
#   theme(plot.tag.position = c(0, 1),
#         plot.tag = element_text(size = 50, family="Times New Roman", face = "bold", hjust = 0, vjust = 0))
ggsave(filename = "all.png", plot = plot_all, width = 40, height = 30, dpi = 300)

```

```{r fig.height=10, fig.width=10}
combine_b <- (cos|tea|sips|df.ReproducibilityNetwork_plot) +  plot_annotation(tag_levels = list(c('b'), '1')) & 
  theme(plot.tag.position = c(0, 1),
        plot.tag = element_text(size = 50, family="Times New Roman", face = "bold", hjust = 0, vjust = 0))

combine_t <- osgcn + plot_annotation(tag_levels = 'a') & 
  theme(plot.tag.position = c(0.3, 1),
        plot.tag = element_text(size = 50, family="Times New Roman", face = "bold", hjust = 0, vjust = 0))
```

```{r}
all <- wrap_elements(combine_t) / wrap_elements(combine_b)
#ggsave(filename = "all2.png", plot = all, width = 40, height = 30, dpi = 300)
```

